### PR TITLE
Second chance to learn

### PR DESCRIPTION
**Pull request by YuriiRozhak**
just wanna see how it looks like when doing thigs right.
Would be apreciated if somebody (at least 2 members of our team) will review this changes.

### CODE REVIEW

**Comment by RomanKarpliak** [comment]
approved by Roman

**Review by RomanKarpliak — COMMENTED** [review]
approved

**Comment by Yur4ukMalyi** [comment]
++

**Review by YuriiMalyi — APPROVED** [review]
approved

**Review by nazar9501 — COMMENTED** [review]
approved

**Pull request merged**
